[package]
name = "xdialog"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A small native-ish cross platform dialogs library with zero runtime dependencies."
authors = ["Caelan Sayler <git@caesay.com>"]
repository = "https://github.com/velopack/xdialog"
keywords = ["dialog", "message-box", "messagebox", "cross-platform"]
categories = ["graphics", "gui", "visualization"]

[features]
default = ["fltk-bundled"]
fltk-bundled = ["fltk/fltk-bundled"]

[dependencies]
fltk = "1.4"
log = "0.4"
atomic-counter = "1.0"
lazy_static = "1.5"
font-kit = "0.14"
dark-light = "1.1"
mina = "0.1"
enum-map = "2.7"
