[package]
name = "xdialog"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A small native-ish cross platform dialogs library with zero runtime dependencies."

[dependencies]
fltk = { version = "1.4", features = ["fltk-bundled"] }
log = "0.4"
atomic-counter = "1.0"
lazy_static = "1.5"
font-kit = "0.14"
dark-light = "1.1.1"
