[package]
name = "xdialog"
version = "0.0.1"
edition = "2021"

[dependencies]
fltk = { version = "1.4", features = ["fltk-bundled"] }
fltk-theme = "0.7"
log = "0.4"
atomic-counter = "1.0"
lazy_static = "1.5"
font-kit = "0.14"